version: "3.3"
services:
          
    frontend:
        build:
            context: ../
            dockerfile: ./dockerfiles/dockerfile.frontend
        image: capstone_frontend:latest
        container_name: capstone_frontend
        tty: true
        restart: always
        ports:
            - 80:80
    backend:
        build:
            context: ../
            dockerfile: ./dockerfiles/dockerfile.backend
        image: capstone_backend:latest
        container_name: capstone_backend
        tty: true
        restart: always
        ports:
            - 3030:3030
    
        
