version: "3.3"
services:
          
    frontend:
        build:
            context: ../
            dockerfile: ./dockerfiles/dockerfile.frontend
        image: capstone_frontend:${CIRCLE_WORKFLOW_ID:0:7}
        container_name: capstone_frontend
        tty: true
        restart: always
        ports:
            - 80:80
    backend:
        build:
            context: ../
            dockerfile: ./dockerfiles/dockerfile.backend
        image: capstone_backend:${CIRCLE_WORKFLOW_ID:0:7}
        container_name: capstone_backend
        environment:
            - TYPEORM_CONNECTION 
            - TYPEORM_ENTITIES 
            - TYPEORM_HOST 
            - TYPEORM_USERNAME
            - TYPEORM_PASSWORD
            - TYPEORM_DATABASE
            - TYPEORM_MIGRATIONS 
            - TYPEORM_MIGRATIONS_DIR
        tty: true
        restart: always
        ports:
            - 3030:3030
    
        
