FROM node:13.8.0-stretch

RUN echo ---$TYPEORM_CONNECTION

# Create app directory
WORKDIR /usr/src/app

COPY ./backend/dist/ .

RUN npm install pm2@latest -g

EXPOSE 80 443 3030

ENTRYPOINT ["pm2","start","npm","--","start"]