apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
      - image: 956722820961.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr-frontend:latest
        name: udacity-container-ml
        resources: {}
status: {}
