apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
    nodePort: 8000
  selector:
    app: app
  type: NodePort
status:
  loadBalancer: {}
