apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: capstone-frontend
  name: capstone-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: capstone-frontend
    spec:
      containers:
      - image: 956722820961.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr-frontend:FRONTEND_IMAGE_VERSION
        name: capstone-ecr-frontend
        imagePullPolicy: "Always"
        resources: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: capstone-backend
  name: capstone-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: capstone-backend
    spec:
      containers:
      - image: 956722820961.dkr.ecr.us-east-2.amazonaws.com/capstone-ecr-backend:BACKEND_IMAGE_VERSION
        name: capstone-ecr-backend
        imagePullPolicy: "Always"
        resources: {}
status: {}
