apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: capstone-frontend
  name: capstone-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: capstone-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: capstone-backend
  name: capstone-backend
spec:
  ports:
  - port: 3030
    protocol: TCP
    targetPort: 3030
  selector:
    app: capstone-backend
  type: LoadBalancer
status:
  loadBalancer: {}
